apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-items
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: tm-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
spec:
  tls:
    - hosts:
      - items.playmonumenta.com
  rules:
    - host: items.playmonumenta.com
      http:
        paths:
          - backend:
              serviceName: web-items
              servicePort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: web-items
  namespace: default
  labels:
    app: web-items
spec:
  type: ClusterIP
  selector:
    app: web-items
  ports:
    - name: web-items
      port: 3000
      targetPort: 3000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-items
  namespace: default
  labels:
    app: web-items
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-items
  template:
    metadata:
      labels:
        app: web-items
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - monumenta-12
      containers:
        - name: otm
          image: docker.pkg.github.com/teammonumenta/monumenta-website/monumenta-items
          ports:
          - containerPort: 3000
          resources:
            limits:
              cpu: 500m
              memory: 768Mi
      imagePullSecrets:
      - name: githubcred

